# Site settings
logo: "./assets/images/headshot.jpg"
title: Sopuruchi Chisom
description: Unleashing Insights from Data ğŸŒ | Insight Whisperer ğŸŒŸ 

theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-feed

# Navigation
navbar_links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
